Migrate-to-pyproject-toml (#6)
* Refactor: migrate to pyproject.toml

* Update Makefile to use 'uv' for pip commands and replace 'black'
  with 'ruff' for formatting and linting.

* ci: update Python setup and build in workflows

* Modify pypi-publish.yml to use python -m build instead of
  setup.py sdist for package building.
* Add twine check step to verify package before publishing.

* style: run ruff formatter

* Fix: update build and hatchling dependencies

Added specific versions for build and hatchling to ensure
compatibility and stability in the project setup.

* style: fix ruff linting issues

* ci: use uv in workflows

* fix: add missing newline at end of run-tests.sh

* fix ci error: Run uv run ./run-tests.sh
   error: Failed to spawn: `./run-tests.sh`
   Caused by: Exec format error (os error 8)

* ci: fix can't find hatchling

* fix ERROR Backend 'hatchling.build' is not available.

* tests: fix tests script and omit check-manifest

* remove check-manifest dep as its soon deprecated
* fix tests unbound args error

* fix: pkg_resources is deprecated as an API

* fix warning pkg_resources is deprecated as an API